In [15]:
import pandas as pd

df = pd.read_csv("../data/raw/Card_Aprov_Pre.csv")

df.head()

,Gênero,Idade,Dívida,Casado(a),Cliente do Banco,Setor da Indústria,Etnia,Anos Empregado,Inadimplência Anterior,Empregado(a),Pontuação de Crédito,Carteira de Motorista,Cidadania,Código Postal,Renda,Aprovado
0,1,30.83,0.000,1,1,7,4,1.25,1,1,1,0,0,202,0,1
1,0,58.67,4.460,1,1,9,1,3.04,1,1,6,0,0,43,560,1
2,0,24.50,0.500,1,1,9,1,1.50,1,0,0,0,0,280,824,1
3,1,27.83,1.540,1,1,7,4,3.75,1,1,5,1,0,100,3,1
4,1,20.17,5.625,1,1,7,4,1.71,1,0,0,0,1,120,0,1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Gênero                  672 non-null    int64
 1   Idade                   672 non-null    float64
 2   Dívida                  672 non-null    float64
 3   Casado(a)               672 non-null    int64
 4   Cliente do Banco        672 non-null    int64
 5   Setor da Indústria      672 non-null    int64
 6   Etnia                   672 non-null    int64
 7   Anos Empregado          672 non-null    float64
 8   Inadimplência Anterior  672 non-null    int64
 9   Empregado(a)            672 non-null    int64
 10  Pontuação de Crédito    672 non-null    int64
 11  Carteira de Motorista   672 non-null    int64
 12  Cidadania               672 non-null    int64
 13  Código Postal           672 non-null    int64
 14  Renda                   672 non-null    int64
 15  Aprovado                672 non-null    int64
dtypes: float64(3), int64(13)
memory usage: 84.1 KB

In [11]:
df.describe()

,Gênero,Idade,Dívida,Casado(a),Cliente do Banco,Setor da Indústria,Etnia,Anos Empregado,Inadimplência Anterior,Empregado(a),Pontuação de Crédito,Carteira de Motorista,Cidadania,Código Postal,Renda,Aprovado
count,672.000000,672.000000,672.000000,672.00000,672.000000,672.000000,672.000000,672.000000,672.000000,672.000000,672.000000,672.000000,672.000000,672.000000,672.000000,672.000000
mean,0.697917,30.541652,4.607924,0.75744,0.760417,5.544643,2.855655,2.151391,0.517857,0.422619,2.383929,0.458333,0.104167,184.436012,1018.812500,0.440476
std,0.459503,10.359295,4.826367,0.42895,0.427147,3.436167,1.502605,3.183523,0.500053,0.494344,4.878394,0.498632,0.338112,174.283969,5264.046919,0.496814
min,0.000000,13.750000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,22.580000,1.000000,1.00000,1.000000,3.000000,1.000000,0.165000,0.000000,0.000000,0.000000,0.000000,0.000000,75.750000,0.000000,0.000000
50%,1.000000,28.250000,2.710000,1.00000,1.000000,5.000000,4.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,160.000000,4.000000,0.000000
75%,1.000000,36.670000,7.000000,1.00000,1.000000,8.000000,4.000000,2.551250,1.000000,1.000000,3.000000,1.000000,0.000000,280.000000,397.000000,1.000000
max,1.000000,60.080000,28.000000,1.00000,1.000000,13.000000,4.000000,28.500000,1.000000,1.000000,67.000000,1.000000,2.000000,2000.000000,100000.000000,1.000000

In [13]:
df.isnull().sum()

Gênero                    0
Idade                     0
Dívida                    0
Casado(a)                 0
Cliente do Banco          0
Setor da Indústria        0
Etnia                     0
Anos Empregado            0
Inadimplência Anterior    0
Empregado(a)              0
Pontuação de Crédito      0
Carteira de Motorista     0
Cidadania                 0
Código Postal             0
Renda                     0
Aprovado                  0
dtype: int64

In [14]:
df["Aprovado"].value_counts()

Aprovado
0    376
1    296
Name: count, dtype: int64